# Generated by Django 4.2.3 on 2023-07-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_faux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='faux',
        ),
    ]
